
[build]
  publish = "dist"

# Redirect rule for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Exclude sitemap.xml from the SPA redirect
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
