
[build]
  publish = "dist"

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

# Redirect rule for SPA - this comes after the sitemap rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
